In [1]:
### Empezamos importando todo

import pandas as pd
import numpy as np

import sys
sys.path.append('../')
import src.funciones as f

In [2]:
df = pd.read_excel('datos/BASE RT- EMBAJADORES - PRUEBA.xlsx')

Anotaciones: 
- 47 filas y 32 columnas
- 1 variable fecha, 8 decimales y 23 texto

In [3]:
df

,Fecha,Acción realizada,Zona / Localidad,Nombre del maestro,Nombre del comercial,Nombre del Asesor,Teléfono del maestro,Influencer / Embajador de zona,Origen del Abordaje,Marca usada al momento del abordaje,...,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,¿Reportó alguna queja?,Tipo de queja,¿Fue resuelta?,Ferretería donde compra,Comentarios adicionales o sugerencias,Comunicado al comercial,LAT,LONG
0,2025-04-01,PRIMERA VISITA,HAINA,ROBERT PEÑA,YANIRIS,Amauris Pichardo,8.292758e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,SI,RENDIMIENTO,SI,FERRETERIA FAUSTO,NaN,SI,18.413131,-70.027869
1,2025-04-03,PRIMERA VISITA,HAINA,FREDDY PEREZ,YANIRIS,Amauris Pichardo,8.297867e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,SI,18.423568,-70.028511
2,2025-05-02,PRIMERA VISITA,HAINA,ANTONIO CASTILLO,YANIRIS,Amauris Pichardo,8.297855e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,SI,COLOR,SI,FERRETERIA LA HACIENDA,NaN,SI,18.428213,-70.017939
3,2025-04-09,PRIMERA VISITA,HAINA,WASCAR PEREZ,YANIRIS,Amauris Pichardo,8.099425e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,DOMICEM,...,NaN,NaN,NaN,NaN,NaN,FAUSTO / AXEL,NaN,SI,18.419162,-70.030863
4,2025-03-15,PRIMERA VISITA,HAINA,RAFAEL PIMENTEL,YANIRIS,Amauris Pichardo,8.492138e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,SI,18.434340,-70.023163
5,2025-04-07,PRIMERA VISITA,HAINA,CANDIDO MARRERO,YANIRIS,Amauris Pichardo,8.093341e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,SI,RESISTENCIA,NO,TEO,NaN,SI,18.425123,-70.034791
6,2025-04-25,PRIMERA VISITA,HAINA,JUAN FRIAS,YANIRIS,Amauris Pichardo,8.297807e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA LA HACIENDA,NaN,SI,18.425309,-70.026714
7,2025-05-16,PRIMERA VISITA,LOS ALCARRIZOS,FRANDELY,PAMELA,Amauris Pichardo,8.496304e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,CIBAO,...,NaN,NaN,SI,COLOR,SI,FERREBEGO,NaN,SI,18.518884,-70.033367
8,2025-05-19,PRIMERA VISITA,LOS ALCARRIZOS,JOSE MANUEL,PAMELA,Amauris Pichardo,8.095021e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,DE LEON RIVAS,NaN,SI,18.519046,-70.040663
9,2025-05-19,PRIMERA VISITA,LOS ALCARRIZOS,LUCA BERNARD,PAMELA,Amauris Pichardo,NaN,JUAN CARLOS,IDENTIFICADO EN OBRA,NaN,...,NaN,NaN,NaN,NaN,NaN,DE LEON RIVAS,NaN,SI,18.534346,-70.053795
10,2025-06-04,PRIMERA VISITA,LAGUNAS DE NISIBON,JULIAN,SURI,Ricardo Rodriguez,8.297857e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,SANTO DOMINGO,...,NaN,NaN,SI,COLOR,NO,FERRETERIA CASTILLO,NaN,SI,18.840799,-68.667164
11,2025-06-04,PRIMERA VISITA,LAGUNAS DE NISIBON,"JOSE CESAREO ""PAJARITO""",SURI,Ricardo Rodriguez,8.095150e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,PANAM,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA CASTILLO,ADEMAS DE LA SITUACION CON EL COLOR DEL PRODUC...,SI,18.831912,-68.667776
12,2025-05-23,PRIMERA VISITA,SAN JUAN,VICTOR VARGAS,LUIS,Amauris Pichardo,8.297645e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA ARSENILIA,NaN,SI,18.802224,-71.225933
13,2025-05-23,PRIMERA VISITA,SAN JUAN,FREDDY,LUIS,Amauris Pichardo,8.096686e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA HUMBERTO,NaN,SI,18.748100,-71.194446
14,2025-05-23,PRIMERA VISITA,SAN JUAN,CHAN,LUIS,Amauris Pichardo,8.293270e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,SI,RENDIMIENTO,SI,FERRETERIA HUMBERTO,NaN,SI,18.748100,-71.194446
15,2025-04-24,PRIMERA VISITA,SABANA IGLESIA,IGNACIO RODRIGUEZ,MERCEDES,Siquio Salazar,8.097618e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,DOMICEM,...,8.096718e+09,50.0,NaN,NaN,NaN,CENTRO FERRETERO SABANA IGLESIA,NaN,SI,19.285584,-70.737256
16,2025-04-24,PRIMERA VISITA,SABANA IGLESIA,MERISIER,MERCEDES,Siquio Salazar,NaN,JUAN CARLOS,REFERIDO POR COMERCIAL,DOMICEM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,19.330109,-70.757003
17,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,JESUS PINEDA,RAQUEL,Amauris Pichardo,8.294261e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,MARTINEZ PACHA,NaN,SI,18.548910,-70.504053
18,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,CRISTIAN DIAZ,RAQUEL,Amauris Pichardo,8.096130e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.543865,-70.505083
19,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FRANCISCO,RAQUEL,Amauris Pichardo,8.292627e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.543946,-70.509632
20,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FREDDY ENCARNACION,RAQUEL,Amauris Pichardo,8.096538e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.537029,-70.509889
21,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,LECLES ELIUS,RAQUEL,Amauris Pichardo,8.094977e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,15.0,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.534344,-70.506971
22,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FRANCIS FILOGENE,RAQUEL,Amauris Pichardo,8.298920e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,80.0,NaN,NaN,NaN,FERNANDEZ,NaN,SI,18.551758,-70.509031
23,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,FERNANDO PETTER,RAQUEL,Amauris Pichardo,8.296336e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,125.0,NaN,NaN,NaN,FERRETERIA JUANA,NaN,SI,18.542970,-70.510576
24,2025-07-15,PRIMERA VISITA,SAN JOSE DE OCOA,PITTER ABERA,RAQUEL,Amauris Pichardo,8.494928e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,85.0,NaN,NaN,NaN,FERREFACIL,NaN,SI,18.587821,-70.498609
25,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,JESUS PINEDA,RAQUEL,Amauris Pichardo,8.294261e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,60.0,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
26,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,CRISTIAN DIAZ,RAQUEL,Amauris Pichardo,8.096130e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
27,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FRANCISCO,RAQUEL,Amauris Pichardo,8.292627e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
28,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FREDDY ENCARNACION,RAQUEL,Amauris Pichardo,8.096538e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI,NaN,NaN
29,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,LECLESES ELIUS,RAQUEL,Amauris Pichardo,8.094977e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
30,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FERNANDO PETTER,RAQUEL,Amauris Pichardo,8.298920e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
31,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,FRANCIS FILOGENE,RAQUEL,Amauris Pichardo,8.296336e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
32,2025-07-22,SEGUIMIENTO,SAN JOSE DE OCOA,PITTER ABERA,RAQUEL,Amauris Pichardo,8.494928e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
33,2025-04-08,SEGUIMIENTO,HAINA,ANTONIO CASTILLO,YANIRIS,Amauris Pichardo,8.297855e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
34,2025-04-15,SEGUIMIENTO,HAINA,RAFAEL PIMENTEL,YANIRIS,Amauris Pichardo,8.492138e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN
35,2025-06-27,PRIMERA VISITA,HAINA,DARIO JIMENEZ,YANIRIS,Amauris Pichardo,8.099530e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.412014,-70.035831
36,2025-06-27,PRIMERA VISITA,HAINA,RAMON ALVAREZ,YANIRIS,Amauris Pichardo,8.292974e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA LA HACIENDA,NaN,NO,18.420711,-70.037924
37,2025-06-27,PRIMERA VISITA,HAINA,WLIKIN DE OLEO,YANIRIS,Amauris Pichardo,8.093996e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.405508,-70.039439
38,2025-06-27,PRIMERA VISITA,HAINA,ROBERTO JAVIER,YANIRIS,Amauris Pichardo,8.098619e+09,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,FERRETERIA FAUSTO,NaN,NO,18.409617,-70.026737
39,2025-04-26,PRIMERA VISITA,AZUA,WILLIAM MEDRANO,RAQUEL,Amauris Pichardo,8.097103e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.450493,-70.745135
40,2025-04-26,PRIMERA VISITA,AZUA,ESQUIA ARVELO,RAQUEL,Amauris Pichardo,8.292090e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.458820,-70.727987
41,2025-04-26,PRIMERA VISITA,AZUA,WILLY URBAEZ,RAQUEL,Amauris Pichardo,8.292940e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.458820,-70.754321
42,2025-04-26,PRIMERA VISITA,AZUA,JOSE MANUEL,RAQUEL,Amauris Pichardo,8.292165e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.441004,-70.726966
43,2025-04-26,PRIMERA VISITA,AZUA,RADAMES ORTIZ,RAQUEL,Amauris Pichardo,8.096760e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.449331,-70.711860
44,2025-04-26,PRIMERA VISITA,AZUA,NICOLAS ROSARIO,RAQUEL,Amauris Pichardo,8.292964e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,18.464242,-70.726150
45,2025-04-26,PRIMERA VISITA,AZUA,RAFAEL MERO,RAQUEL,Amauris Pichardo,8.494240e+09,JUAN CARLOS,REFERIDO POR COMERCIAL,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.444684,-70.735336
46,2025-04-26,PRIMERA VISITA,AZUA,JOSE DEL CARMEN,RAQUEL,Amauris Pichardo,NaN,JUAN CARLOS,IDENTIFICADO EN OBRA,ARGOS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.450493,-70.747789

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 32 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   Fecha                                             47 non-null     datetime64[ns]
 1   Acción realizada                                  47 non-null     object
 2   Zona / Localidad                                  47 non-null     object
 3   Nombre del maestro                                47 non-null     object
 4   Nombre del comercial                              47 non-null     object
 5   Nombre del Asesor                                 47 non-null     object
 6   Teléfono del maestro                              44 non-null     float64
 7   Influencer / Embajador de zona                    47 non-null     object
 8   Origen del Abordaje                               47 non-null     object
 9   Marca usada al momento del abordaje               46 non-null     object
 10  Motivo de inconformidad con Titan                 47 non-null     object
 11  ¿Probó fundas Titan durante la visita?            47 non-null     object
 12  Cantidad de fundas dejadas para prueba            42 non-null     float64
 13  Resultado de prueba en obra                       41 non-null     object
 14  Comentarios técnicos / percepción del maestro     6 non-null      object
 15  ¿Aceptó volver a probar Titan?                    7 non-null      object
 16  ¿Se registró en Conéctate Maestro?                25 non-null     object
 17  ¿Se aplicó bono?                                  15 non-null     object
 18  Fecha de redención de bono                        0 non-null      float64
 19  # de fundas compradas luego del abordaje          6 non-null      float64
 20  ¿Ha influenciado a otro maestro?                  14 non-null     object
 21  Nombre del maestro influenciado                   6 non-null      object
 22  Teléfono del influenciado                         1 non-null      float64
 23  Cantidad de fundas compradas por el influenciado  6 non-null      float64
 24  ¿Reportó alguna queja?                            6 non-null      object
 25  Tipo de queja                                     6 non-null      object
 26  ¿Fue resuelta?                                    6 non-null      object
 27  Ferretería donde compra                           28 non-null     object
 28  Comentarios adicionales o sugerencias             1 non-null      object
 29  Comunicado al comercial                           45 non-null     object
 30  LAT                                               37 non-null     float64
 31  LONG                                              37 non-null     float64
dtypes: datetime64[ns](1), float64(8), object(23)
memory usage: 11.9+ KB

In [11]:
df.describe()

,Fecha,Teléfono del maestro,Cantidad de fundas dejadas para prueba,Fecha de redención de bono,# de fundas compradas luego del abordaje,Teléfono del influenciado,Cantidad de fundas compradas por el influenciado,LAT,LONG
count,47,4.400000e+01,42.000000,0.0,6.0000,1.000000e+00,6.000000,37.000000,37.000000
mean,2025-05-31 05:06:22.978723328,8.245535e+09,6.380952,NaN,213.5000,8.096718e+09,69.166667,18.561739,-70.346784
min,2025-03-15 00:00:00,8.093341e+09,2.000000,NaN,10.0000,8.096718e+09,15.000000,18.405508,-71.225933
25%,2025-04-26 00:00:00,8.096741e+09,5.000000,NaN,38.7500,8.096718e+09,52.500000,18.428213,-70.727987
50%,2025-05-23 00:00:00,8.292849e+09,5.500000,NaN,187.5000,8.096718e+09,70.000000,18.464242,-70.505083
75%,2025-07-15 00:00:00,8.297855e+09,9.000000,NaN,325.0000,8.096718e+09,83.750000,18.548910,-70.033367
max,2025-07-22 00:00:00,8.496304e+09,10.000000,NaN,536.0000,8.096718e+09,125.000000,19.330109,-68.667164
std,NaN,1.364865e+08,2.208105,NaN,207.1847,NaN,37.069754,0.218534,0.551803

La fecha viene desde marzo hasta el mes de julio.

In [6]:
df.nunique()

Fecha                                               18
Acción realizada                                     2
Zona / Localidad                                     7
Nombre del maestro                                  37
Nombre del comercial                                 6
Nombre del Asesor                                    3
Teléfono del maestro                                34
Influencer / Embajador de zona                       1
Origen del Abordaje                                  2
Marca usada al momento del abordaje                  5
Motivo de inconformidad con Titan                    3
¿Probó fundas Titan durante la visita?               2
Cantidad de fundas dejadas para prueba               9
Resultado de prueba en obra                          4
Comentarios técnicos / percepción del maestro        4
¿Aceptó volver a probar Titan?                       2
¿Se registró en Conéctate Maestro?                   2
¿Se aplicó bono?                                     2
Fecha de redención de bono                           0
# de fundas compradas luego del abordaje             5
¿Ha influenciado a otro maestro?                     2
Nombre del maestro influenciado                      6
Teléfono del influenciado                            1
Cantidad de fundas compradas por el influenciado     6
¿Reportó alguna queja?                               1
Tipo de queja                                        3
¿Fue resuelta?                                       2
Ferretería donde compra                             14
Comentarios adicionales o sugerencias                1
Comunicado al comercial                              2
LAT                                                 34
LONG                                                36
dtype: int64

In [7]:
df.shape

(47, 32)

In [9]:
f.exploracion_dataframe(df)

El número de datos es 47 y el de columnas es 32

 .....................

Los duplicados que tenemos en el conjunto de datos son: 0

 .....................

Los nulos que tenemos en el conjunto de datos son:

                                                     %_nulos
Teléfono del maestro                                6.382979
Marca usada al momento del abordaje                 2.127660
Cantidad de fundas dejadas para prueba             10.638298
Resultado de prueba en obra                        12.765957
Comentarios técnicos / percepción del maestro      87.234043
¿Aceptó volver a probar Titan?                     85.106383
¿Se registró en Conéctate Maestro?                 46.808511
¿Se aplicó bono?                                   68.085106
Fecha de redención de bono                        100.000000
# de fundas compradas luego del abordaje           87.234043
¿Ha influenciado a otro maestro?                   70.212766
Nombre del maestro influenciado                    87.234043
Teléfono del influenciado                          97.872340
Cantidad de fundas compradas por el influenciado   87.234043
¿Reportó alguna queja?                             87.234043
Tipo de queja                                      87.234043
¿Fue resuelta?                                     87.234043
Ferretería donde compra                            40.425532
Comentarios adicionales o sugerencias              97.872340
Comunicado al comercial                             4.255319
LAT                                                21.276596
LONG                                               21.276596

 .....................

Los tipos de las columnas son:

                                                       tipo_dato
Fecha                                             datetime64[ns]
Acción realizada                                          object
Zona / Localidad                                          object
Nombre del maestro                                        object
Nombre del comercial                                      object
Nombre del Asesor                                         object
Teléfono del maestro                                     float64
Influencer / Embajador de zona                            object
Origen del Abordaje                                       object
Marca usada al momento del abordaje                       object
Motivo de inconformidad con Titan                         object
¿Probó fundas Titan durante la visita?                    object
Cantidad de fundas dejadas para prueba                   float64
Resultado de prueba en obra                               object
Comentarios técnicos / percepción del maestro             object
¿Aceptó volver a probar Titan?                            object
¿Se registró en Conéctate Maestro?                        object
¿Se aplicó bono?                                          object
Fecha de redención de bono                               float64
# de fundas compradas luego del abordaje                 float64
¿Ha influenciado a otro maestro?                          object
Nombre del maestro influenciado                           object
Teléfono del influenciado                                float64
Cantidad de fundas compradas por el influenciado         float64
¿Reportó alguna queja?                                    object
Tipo de queja                                             object
¿Fue resuelta?                                            object
Ferretería donde compra                                   object
Comentarios adicionales o sugerencias                     object
Comunicado al comercial                                   object
LAT                                                      float64
LONG                                                     float64

 .....................

Los valores que tenemos para las columnas categóricas son:
La columna Acción realizada tiene los siguientes valores únicos:

                  count
Acción realizada
PRIMERA VISITA       37
SEGUIMIENTO          10

La columna Zona / Localidad tiene los siguientes valores únicos:

                    count
Zona / Localidad
SAN JOSE DE OCOA       16
HAINA                  13
AZUA                    8
LOS ALCARRIZOS          3
SAN JUAN                3
LAGUNAS DE NISIBON      2
SABANA IGLESIA          2

La columna Nombre del maestro tiene los siguientes valores únicos:

                         count
Nombre del maestro
CRISTIAN DIAZ                2
JOSE MANUEL                  2
FRANCISCO                    2
FERNANDO PETTER              2
JESUS PINEDA                 2
PITTER ABERA                 2
FRANCIS FILOGENE             2
FREDDY ENCARNACION           2
RAFAEL PIMENTEL              2
ANTONIO CASTILLO             2
WILLY URBAEZ                 1
ESQUIA ARVELO                1
RADAMES ORTIZ                1
ROBERTO JAVIER               1
WLIKIN DE OLEO               1
RAMON ALVAREZ                1
DARIO JIMENEZ                1
LECLESES ELIUS               1
NICOLAS ROSARIO              1
RAFAEL MERO                  1
WILLIAM MEDRANO              1
ROBERT PEÑA                  1
LECLES ELIUS                 1
FREDDY PEREZ                 1
MERISIER                     1
IGNACIO RODRIGUEZ            1
CHAN                         1
FREDDY                       1
VICTOR VARGAS                1
JOSE CESAREO "PAJARITO"      1
JULIAN                       1
LUCA BERNARD                 1
FRANDELY                     1
JUAN FRIAS                   1
CANDIDO MARRERO              1
WASCAR PEREZ                 1
JOSE DEL CARMEN              1

La columna Nombre del comercial tiene los siguientes valores únicos:

                      count
Nombre del comercial
RAQUEL                   24
YANIRIS                  13
PAMELA                    3
LUIS                      3
SURI                      2
MERCEDES                  2

La columna Nombre del Asesor tiene los siguientes valores únicos:

                   count
Nombre del Asesor
Amauris Pichardo      43
Ricardo Rodriguez      2
Siquio Salazar         2

La columna Influencer / Embajador de zona tiene los siguientes valores únicos:

                                count
Influencer / Embajador de zona
JUAN CARLOS                        47

La columna Origen del Abordaje tiene los siguientes valores únicos:

                        count
Origen del Abordaje
IDENTIFICADO EN OBRA       31
REFERIDO POR COMERCIAL     16

La columna Marca usada al momento del abordaje tiene los siguientes valores únicos:

                                     count
Marca usada al momento del abordaje
ARGOS                                   40
DOMICEM                                  3
CIBAO                                    1
SANTO DOMINGO                            1
PANAM                                    1

La columna Motivo de inconformidad con Titan tiene los siguientes valores únicos:

                                   count
Motivo de inconformidad con Titan
COLOR                                 32
RESISTENCIA                           10
DISPONIBILIDAD                         5

La columna ¿Probó fundas Titan durante la visita? tiene los siguientes valores únicos:

                                        count
¿Probó fundas Titan durante la visita?
SI                                         42
NO                                          5

La columna Resultado de prueba en obra tiene los siguientes valores únicos:

                             count
Resultado de prueba en obra
POSITIVO                        33
NEUTRAL                          4
NEGATIVO                         2
NO REALIZADA                     2

La columna Comentarios técnicos / percepción del maestro tiene los siguientes valores únicos:

                                                    count
Comentarios técnicos / percepción del maestro
POCA RESISTENCIA                                        2
BAJO RENDIMIENTO                                        2
NO TIENE LA RESISTENCIA ESPERADA Y MENOR RENDIM...      1
MAL COLOR                                               1

La columna ¿Aceptó volver a probar Titan? tiene los siguientes valores únicos:

                                count
¿Aceptó volver a probar Titan?
NO                                  5
SI                                  2

La columna ¿Se registró en Conéctate Maestro? tiene los siguientes valores únicos:

                                    count
¿Se registró en Conéctate Maestro?
SI                                     21
NO                                      4

La columna ¿Se aplicó bono? tiene los siguientes valores únicos:

                  count
¿Se aplicó bono?
SI                   10
NO                    5

La columna ¿Ha influenciado a otro maestro? tiene los siguientes valores únicos:

                                  count
¿Ha influenciado a otro maestro?
NO                                    8
SI                                    6

La columna Nombre del maestro influenciado tiene los siguientes valores únicos:

                                 count
Nombre del maestro influenciado
LEO                                  1
JUAN PEREZ                           1
MANUEL                               1
IVAN                                 1
CRISTIAN                             1
JOSE                                 1

La columna ¿Reportó alguna queja? tiene los siguientes valores únicos:

                        count
¿Reportó alguna queja?
SI                          6

La columna Tipo de queja tiene los siguientes valores únicos:

               count
Tipo de queja
COLOR              3
RENDIMIENTO        2
RESISTENCIA        1

La columna ¿Fue resuelta? tiene los siguientes valores únicos:

                count
¿Fue resuelta?
SI                  4
NO                  2

La columna Ferretería donde compra tiene los siguientes valores únicos:

                                 count
Ferretería donde compra
FERRETERIA FAUSTO                    6
FERREFACIL                           5
FERRETERIA LA HACIENDA               3
DE LEON RIVAS                        2
FERRETERIA CASTILLO                  2
FERRETERIA HUMBERTO                  2
FAUSTO / AXEL                        1
TEO                                  1
FERREBEGO                            1
FERRETERIA ARSENILIA                 1
CENTRO FERRETERO SABANA IGLESIA      1
MARTINEZ PACHA                       1
FERNANDEZ                            1
FERRETERIA JUANA                     1

La columna Comentarios adicionales o sugerencias tiene los siguientes valores únicos:

                                                    count
Comentarios adicionales o sugerencias
ADEMAS DE LA SITUACION CON EL COLOR DEL PRODUCT...      1

La columna Comunicado al comercial  tiene los siguientes valores únicos:

                          count
Comunicado al comercial
SI                           29
NO                           16

Tenemos: 
- 2 tipos de acciones (primera visita con 17)
- 7 localidades diferentes (San Jose de Ocoa tiene 16, le sigue Haina on 13)
- 37 nombres de maestros (varios se repiten en 2 ocasiones)
- 6 comerciales (raquel lidera con 24)
- 3 asesores (Amauris Pichardo es quien tiene más presencia 43)
- 1 influencer 
- 2 origenes de abordaje (lidera identificado en obra 31)
- 5 tipos de marcas (Argos lidera con 40)
- 3 motivos de inconformidad (lidera el color con 32)
- 42 de las ocasiones probaron el Titan durante la visita
- 33 descripciones tuvieron un resultado de prueba positivo
- 21 veces se registraron en Conéctate Maestro
- Solo en 10 ocasiones se aplicó Bono
- 6 casos reportaron quejas
- Reportaron 14 ferreterías diferentes
- 29 de comunicaron al comercial, 16 no